#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend cryptotechcoder
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 439003-web-01 34.230.88.74 check
    server 439003-web-02 54.204.241.160:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
